bpf: don't use a negative errno
thread 'main' panicked at [...]libbpf-rs-0.22.1/src/error.rs:334:9:
OS error code should be positive integer; got: -7

Also triggered for pin_hid_bpf_prog(), assuming run_syscall_prog() has
the same issue.

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>